AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'My serverless Express.js app'

Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Events:
        MyAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY